### PR TITLE
Fixed karma test filters. Switched from IFrame to UIComponent for test coverage.

### PR DESCRIPTION
**Pull request by mcanalesmayo**
## Current vs expected behaviour
Currently, running ``npm test`` succeeds but there are no entries in the coverage report:
```
TOTAL: 31 SUCCESS
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
```

After the changes in this PR running the same command produces the following output:
```
TOTAL: 31 SUCCESS
-------------------------|----------|----------|----------|----------|----------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------|----------|----------|----------|----------|----------------|
 webapp/                 |    86.67 |       75 |      100 |    86.67 |                |
  Component.js           |    86.67 |       75 |      100 |    86.67 |          58,63 |
 webapp/controller/      |       91 |       72 |    89.47 |       91 |                |
  App.controller.js      |      100 |      100 |      100 |      100 |                |
  BaseController.js      |       75 |        0 |    83.33 |       75 |          51,52 |
  ErrorHandler.js        |    89.47 |    85.71 |    83.33 |    89.47 |          24,25 |
  NotFound.controller.js |      100 |      100 |      100 |      100 |                |
  Object.controller.js   |    86.21 |       50 |    90.91 |    86.21 |    61,63,64,66 |
  Worklist.controller.js |    96.67 |    83.33 |       90 |    96.67 |             99 |
 webapp/localService/    |      100 |    93.75 |      100 |      100 |                |
  mockserver.js          |      100 |    93.75 |      100 |      100 |                |
 webapp/model/           |      100 |      100 |      100 |      100 |                |
  formatter.js           |      100 |      100 |      100 |      100 |                |
  models.js              |      100 |      100 |      100 |      100 |                |
-------------------------|----------|----------|----------|----------|----------------|
All files                |    93.04 |    80.39 |    92.86 |    93.04 |                |
-------------------------|----------|----------|----------|----------|----------------|
```

## Changes
- Fixed karma preprocessor filters in the test step as done in OpenUI5 sample app: https://github.com/SAP/openui5-sample-app/pull/35
- Switched integration tests from IFrame to UIComponent to be able to get coverage.
- Adapted mockserver and integration tests.
- Switched from PhantomJS to HeadlessChrome and updated devDependencies as done in OpenUI5 sample app: https://github.com/SAP/openui5-sample-app/pull/36

## Remarks
It was needed to lower the coverage acceptance criteria to **global 90/80/90/90** (please see changes in ``karma-ci.conf.js`` file) so that ``npm test`` step doesn't fail with the currently implemented tests, as it was previously 100/100/100/100. IMHO it's still an acceptable criteria though.

### CODE REVIEW

**Comment by Michadelic** [comment]
Hi @mcanalesmayo and thank you so much for this pull.
We will review it and get back to you soon.

Indeed, our karma setup was not working yet, and we have internally compiled a draft for a new Karma Setup as well, will match and align with your suggestions to bring it into this template

Kind Regards,
Michael

**Comment by mcanalesmayo** [comment]
Thanks @Michadelic.
I had some doubts on when to initialize and shutdown of the mockserver in the tests. I considered these options:
1. In the ``beforeEach`` and ``afterEach`` hooks of each QUnit module.
2. Or in the arrangements and app teardown of each test, which may give the developer a little bit more flexible.

I went for the first one as I don't think starting up the mockserver is part of the arrangements, but I would like to know your thoughts on this. Anyways, I'll wait for your inputs.

BR,
Marcos.

**Comment by Michadelic** [comment]
Coincidentially we have just merged a change yesterday transforming the "worklist" demo app to component loader. You can check how we did it there:
https://github.com/SAP/openui5/commit/cb5e4bb25327c5598d0b0e2f037c9f9ab52b9d9b

The mock server is restarted in the Startup.js file (formerly called Arrangements.js) in our case, we don't bother shutting it down in the end though, so that's maybe something to consider

We will have a look at your suggestions, too and merge the best out of the two worlds.

Michael

**Comment by Tanbari** [comment]
Hi @mcanalesmayo 
Thanks for your contribution especially to karma. We have implemented it in this pull request https://github.com/SAP/openui5-worklist-app/pull/11

Also, we have added it to 'master-detail' and 'basic-template' templates.

Until now we still discuss the best practice to do karma configuration and we have added an internal repo for that and we will update it with your karma suggestion.

For now, I will keep your pull request
Kind Regards,
Ayham

**Comment by Michadelic** [comment]
Hello @mcanalesmayo, thanks again for your suggestions. As stated before, we were internally discussing our testing strategy and @matz3 worked on a new karma-ui5 version that makes most of the configuration redundant. Please have a look at https://github.com/SAP/openui5-worklist-app/pull/16 for the details.

Leaving this PR open for now just in case there are some gaps between the new testing tools and what you originally proposed.

Thank you and all the best,
Michael

**Comment by mcanalesmayo** [comment]
> Hi @mcanalesmayo
> Thanks for your contribution especially to karma. We have implemented it in this pull request #11
> 
> Also, we have added it to 'master-detail' and 'basic-template' templates.
> 
> Until now we still discuss the best practice to do karma configuration and we have added an internal repo for that and we will update it with your karma suggestion.
> 
> For now, I will keep your pull request
> Kind Regards,
> Ayham

I'm closing this PR then

**Pull request closed without merging**
